name: Build and Package

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "test_*.py"
  build-windows:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build exe with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed main.py --name MySQLAddSchema
      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: MySQLAddSchema-windows
          path: dist/MySQLAddSchema.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Mac App Bundle
        run: |
          pyinstaller --noconfirm --windowed main.py --name MySQLAddSchema
      - name: Upload Mac App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: MySQLAddSchema-mac
          path: dist/MySQLAddSchema.app