name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
        
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
      - name: Deploy Qt dependencies with windeployqt
        run: |
          cd build/Release
          windeployqt.exe add_schema.exe
      - name: Create ZIP file
        run: |
          cd build
          $zipFile = "Release/add_schema.zip"
          Compress-Archive -Path "Release/*" -DestinationPath $zipFile    
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/Release/add_schema.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.1'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev
      - name: Build
        run: |
          echo $RUNNER_WORKSPACE
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/add_schema

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.1'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
      - name: Build
        run: |
          echo $RUNNER_WORKSPACE
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
      - name: Package macOS App
        run: |
          cd build
          macdeployqt add_schema.app -dmg 
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/add_schema.dmg

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Debug file structure
        run: |
          ls -R
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          files: |
            windows-build/*
            linux-build/*
            macos-build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
